name: Fastify Integration Tests

on:
  push:
    branches:
     - main
     - master
     - next
     - 'v*'
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  test:
    name: Fastify Integration Tests
    runs-on: ubuntu-latest
    permissions:
        contents: read
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
            node-version: lts/*

      - name: Install dependencies
        run: npm i --ignore-scripts

      - name: Symlink
        run: npm link

      - name: Test Fastify with light-my-request
        run: |
          git clone https://github.com/fastify/fastify.git --depth 1 &&
          cd fastify &&
          npm i --ignore-scripts &&
          npm link light-my-request &&
          npm run unit
